<script setup>
import { inject, onMounted } from 'vue';
import DetailedProperties from './DetailedProperties.vue';
import FormStep from '@/Components/FormStep.vue';
import { Accordion } from 'flowbite';

const translate = inject('translate');

const props = defineProps({
    siblings: Array,
});

onMounted(() => {
    const accordionTriggers = document.querySelectorAll('[id^="sibling-heading-"]');
    accordionTriggers.forEach(trigger => {
        const config = {
            items: [{
                id: trigger.id,
                triggerEl: trigger,
                targetEl: document.querySelector(`[id="${trigger.id.replace('heading', 'body')}"]`),
                active: false,
            }],
            options: {
                alwaysOpen: true,
                activeClasses: 'bg-gray-100 text-gray-900',
                inactiveClasses: 'bg-gray-50 text-gray-500',
            },
        };
        new Accordion(config.items, config.options);
    });

    /* const accordionConfiguration = {
        items: [
            {
                id: 'alert-properties-heading',
                triggerEl: document.querySelector('#alert-properties-heading'),
                targetEl: document.querySelector('#alert-properties-body'),
                active: alertFiltersCount.value > 0,
            },
            {
                id: 'orchestrator-connection-properties-heading',
                triggerEl: document.querySelector('#orchestrator-connection-properties-heading'),
                targetEl: document.querySelector('#orchestrator-connection-properties-body'),
                active: orchestratorConnectionFiltersCount.value > 0,
            },
        ],
        options: {
            alwaysOpen: true,
            activeClasses: 'bg-gray-100 text-gray-900',
            inactiveClasses: 'bg-gray-50 text-gray-500',
        },
    };

    new Accordion(accordionConfiguration.items, accordionConfiguration.options);  */
});
</script>

<template>
    <FormStep>
        <template #title>
            {{ __('Similar alerts') }}
        </template>
        <template #description>
            <div class="text-sm">
                <p>{{ __('This section serves as a way for users to quickly identify and analyze alerts that are related to the one they are currently working on. By examining the similarities and differences between alerts in the list, users can gain insights into patterns and trends in the alerts generated by their system.') }}</p>
            </div>
        </template>
        <template #form>
            <div class="col-span-6">
                <ul class="w-full">
                    <li v-for="(alert, index) in siblings" :class="{
                        'pb-3': index === 0,
                        'py-3': index !== 0 && index !== (siblings.length - 1),
                        'pt-3': index !== 0 && index === siblings.length - 1,
                    }">
                        <!-- <div class="inline-flex items-center text-base font-semibold text-gray-900">#{{ alert.id_padded }}</div>
                        <div class="flex-1 min-w-0">
                            <p class="flex text-sm text-gray-500">
                                <span class="font-semibold">{{ __('Creation date') }}</span>
                                <span>{{ alert.creation_time }}</span>
                            </p>
                            <p class="text-sm text-gray-500"></p>
                        </div> -->

                        <h2 :id="'sibling-heading-' + alert.id">
                            <button type="button"
                                class="flex items-center justify-center w-full p-2 font-semibold text-md text-gray-500 border border-gray-200 rounded-t-sm hover:bg-gray-100"
                                aria-expanded="false" :aria-controls="'sibling-body-' + alert.id">
                                #{{ alert.id_padded }}
                            </button>
                        </h2>
                        <div :id="'sibling-body-' + alert.id" class="hidden" :aria-labelledby="'sibling-heading-' + alert.id">
                            <div class="p-2 border border-t-0 border-gray-200">
                                <DetailedProperties :form="alert"
                                    :with-notification-name="false" :with-component="false"
                                    :with-orchestrator-connection="false"
                                    :with-resolution-details="true" :with-link="true" />
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </template>
    </FormStep>
</template>